# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: frontend

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
    - '*.yml'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: artifactName
    value: 'frontend'

steps:
- script: |
    echo "Packaging frontend app..."
    mkdir $(Build.ArtifactStagingDirectory)/package
    cp -r static $(Build.ArtifactStagingDirectory)/package/
    cp -r templates $(Build.ArtifactStagingDirectory)/package/
    cp app.py $(Build.ArtifactStagingDirectory)/package/
    cp requirements.txt $(Build.ArtifactStagingDirectory)/package/
  displayName: 'Package Frontend Files'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/package'
    artifact: '$(artifactName)'
    publishLocation: 'pipeline'
  displayName: 'Publish Frontend Pipeline Artifact'
  condition: and(succeeded(), ne(variables['skip_build'], 'true'))
